name: Automated Tests

on:
  pull_request:

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm test
  cypress:
    name: Cypress Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: echo "$GITHUB_USER $GITHUB_PW $COOKIE_NAME $SITE_NAME"
      - run: npm run test:e2e
        env: 
          GITHUB_USER: ${{ secrets.CYPRESS_TEST_OAUTH_USER }}
          GITHUB_PW: ${{ secrets.CYPRESS_TEST_OAUTH_PASSWORD }}
          COOKIE_NAME: ${{ secrets.CYPRESS_TEST_OAUTH_COOKIE_NAME }}
          SITE_NAME: ${{ secrets.CYPRESS_TEST_OAUTH_SITE_NAME }}
          GHUB_ID: ${{ secrets.GHUB_ID }}
          GHUB_SECRET: ${{ secrets.GHUB_SECRET }}
