name: Automated Tests

on:
  pull_request:

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm test
  cypress:
    name: Cypress Ubuntu
    runs-on: ubuntu-latest
    env: 
      CYPRESS_TEST_OAUTH_USER: ${{ secrets.CYPRESS_TEST_OAUTH_USER }},
      CYPRESS_TEST_OAUTH_PASSWORD: ${{ secrets.CYPRESS_TEST_OAUTH_PASSWORD }},
      CYPRESS_TEST_OAUTH_COOKIE_NAME: ${{ secrets.CYPRESS_TEST_OAUTH_COOKIE_NAME }},
      CYPRESS_TEST_OAUTH_SITE_NAME: ${{ secrets.CYPRESS_TEST_OAUTH_SITE_NAME }},
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm run test:e2e
