name: Automated Tests

on:
  pull_request:

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
      - run: npm ci
      - run: npm test
  cypress:
    name: Cypress Ubuntu
    runs-on: ubuntu-24.04
    env: 
      CYPRESS_GITHUB_USER: ${{ secrets.GHUB_OAUTH_USER }}
      CYPRESS_GITHUB_PASSWORD: ${{ secrets.GHUB_OAUTH_PASSWORD }}
      CYPRESS_COOKIE_NAME: "next-auth.session-token"
      CYPRESS_SITE_NAME: "http://localhost:3000/status"
      GHUB_ID: ${{ secrets.GHUB_ID }}
      GHUB_SECRET: ${{ secrets.GHUB_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
          cache: 'npm'
      - name: Install Puppeteer dependencies and Chrome
        run: |
          sudo apt update && sudo apt install -y \
            google-chrome-stable \
            ca-certificates \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3 \
            libexpat1 \
            libfontconfig1 \
            libgbm1 \
            libgcc1 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libnss3 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            lsb-release \
            wget \
            xdg-utils
      - uses: cypress-io/github-action@v6
        with:
          install: true
          start: npm run dev
          wait-on: http://localhost:3000/status
          browser: chrome
          headed: true
          record: false
        env:
          CHROME_BIN: /usr/bin/google-chrome-stable
          CYPRESS_BROWSER_ARGS: "--no-sandbox"